### ISSUE TITLE
Review of bootcamp section 6.3

### ISSUE THREAD

**Issue by snowmang1** [liatrio/devops-bootcamp#239]
## Overview
- May need changes for M1 and also value reasons.

**Comment by snowmang1** [comment]
according to this: https://docs.chef.io/platforms/
chef has direct support for m1. personally I have had some problems with initial setup of chef on m1 but currently I think that is due to my personal setup rather than chef itself.

**Comment by snowmang1** [comment]
This ticket is getting put on hold until I finished my investigation of codifying the deployment.

**Comment by jburns24** [comment]
Moved to addendum closing
