### ISSUE TITLE
Add all the linting to devops-bootcamp

### ISSUE THREAD

**Issue by snowmang1** [liatrio/devops-bootcamp#240]
I was reviewing the devops-bootcamp repo and realized that we didn’t support local development on it well (globally installing npm packages with vulnerability is  ). As a quick and dirty way to get this spun up I leveraged the package choices I found in the liatrio onboarding repo. 

The dev dependency that got added was a linter called remark which we use in the onboarding repo. This got me thinking and looking into other linters we can add specifically for spelling, and clarity. But I also think we can reevaluate the markdown linter. A quick search lead me to this post where someone talked about what they thought were good linters and why. https://earthly.dev/blog/markdown-lint/  

The way I see this ticket there are a few things to research and decide on:

What linters should we add (I am inclined to say for sure a markdown linter and a spelling linter)

Which linter should we use. I am usually inclined to go with tools that get active development, fit our existing tech stack.

And then add these linters. 

I would guess that after adding linters we might find many violations. I would suggest addressing those violations as a fast-follow to keep pr’s segregated

**Comment by ianhundere** [comment]
i also included the `.markdownlint.json` file to easily configure what rules we wanna react on etc
