### ISSUE TITLE
Remove Realworld from the bootcamp

### ISSUE THREAD

**Issue by snowmang1** [liatrio/devops-bootcamp#241]
Realworld is an outdated set of frontend and backend applications intended to function together, but in actuality are quite difficult to configure to work with one another. This causes an unnecessary blocker, halting the learning process of deploying containers to AWS/Azure. Proposing the creation of a simple, Liatrio managed frontend and backend that serves the same learning purpose as Realworld.

It is mostly used throughout chapter 3 with references in chapter 5. First look is linked below.

https://devops-bootcamp.liatr.io/#/3-cloud-computing/3.2.1-s3-cloudfront?id=create-a-website-using-an-s3-bucket
https://codebase.show/projects/realworld

**Comment by dreweth** [comment]
Replaced with DevOps knowledge share in some places.  Also, in another card, swapped in a lightweight version of Real world that did compile as expected.  Closing this ticket.
