### ISSUE TITLE
Creating Github section

### ISSUE THREAD

**Issue by rhoofard** [liatrio/devops-bootcamp#279]
Adding initial Github sections to the bootcamp involving Actions, Projects, API's, and maybe a little bit about Security.  Goal is to create an iterative project where you end up with a pretty flushed out Org, repos, workflows etc to reference later.  Should be easy to add on to.

**Comment by rhoofard** [comment]
Link to branch where it lives [here](https://github.com/liatrio/devops-bootcamp/tree/github-section/9-Github)

**Comment by dreweth** [comment]
@rhoofard - is this an active effort for you?  Just trying to gauge.
