### ISSUE TITLE
Add word cloud to devops bootcamp showing technologies we cover

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#292]
In a recent PR (https://github.com/liatrio/devops-bootcamp/pull/286) we added metadata about the bootcamp. This metadata allows us to to create some visualizations using chart.js. One of the things collected in the metadata is an array of technologies that are used in each exercise. Usuing this data and [chartjs-chart-wordcloud](https://github.com/sgratzl/chartjs-chart-wordcloud) we can create a wordcloud of technologies we use. This would be a good add to the bootcamp landing page

**Comment by densellp** [comment]
@cfculler How far have you gotten into this? I heard you got stuck at one point.
