### ISSUE TITLE
3.2.2 Jenkins replacement - EC2

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#305]
### Learning Goal
Introduction to EC2

The exercise in this section is to spin up two EC2 instances make one a Jenkins server and the other a Jenkins agent. Then run some builds on the hosts. Really Jenkins just servers as a 'thing to install' that also communicates with another host. We can do lots of things here. 

I am not really opposed to keeping this section as Jenkins. Since it is still a relevant CI/CD tool that some of our clients use. If we keep this as Jenkins given we are stripping much of the other Jenkins sections out we should update this section to have more general information about Jenkins and point apprentices to docs so for creating a pipeline.

If we want to remove Jenkins here are a few ideas for alternatives I think would be beneficial:

Grafana -- one node as a Grafana server the other node running a data collection agent like telegraf https://grafana.com/tutorials/stream-metrics-from-telegraf-to-grafana

Ansible -- one node as an Ansible server the other as a node with the Ansible agent. Then apply a simple playbook that installs put a hello world text file on the node with the agent. 

Zabbix server -- setup basic monitor on other node

* Deliverables could use some love here

**Comment by amber-beasley-liatrio** [comment]
Going with option #1, leaving Jenkins in, so there is at least one exercise exposing the campers to Jenkins (since our clients use it and they likely will have to cross paths with it at some point in a DevOps flavored career)

**Comment by jburns24** [comment]
@amber-beasley-liatrio Totally cool with me. If we are going to leave it as Jenkins for this ticket can you add a little blurb at the top introducing campers to Jenkins (this is now the first time they will run into it). Additionally there are some broken links on this page (need to get that functional testing in place) that need updating. 

Also since they will have not ran into Jenkins prior to this exercise can we add a step to create a 'pipeline' that runs some hello world script or something. I would like this to be simple enough that they are not spending to much time creating a pipeline but enough to demonstrate _what_ someone might do with Jenkins.
