### ISSUE TITLE
5.4.2 Jenkins replacement - Helm

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#309]
### Learning Goal
`helm create`

Update Exercise 4 to create a chart to deploy a GH self-hosted runner. This should leverage the image created in previous chapters

**Comment by amber-beasley-liatrio** [comment]
GH self hosted runner in Kubernetes is not clean cut. There are additional resources that need to be deployed (cert manager and GitHub actions controller). I'm planning on those pieces being documented well and leaving the *actual* runner deployment for the learning part of the exercise.

I'm not sure if we were just wanting them to go through the motions of creating a helm chart for the runner alone or getting all of this actually working with the helm chart they wrote.

@jburns24  any thoughts on how involved we want campers to get?

**Comment by amber-beasley-liatrio** [comment]
I've tested the instructions using the GitHub image provided in the GitHub instructions and using someones else's blog post to get it working on Minikube. 

I think campers will probably have a hard time with the differences between the image they created for a GitHub runner vs what is provided in the directions by GitHub. https://github.com/actions/actions-runner-controller/blob/master/docs/quickstart.md#deploy-and-configure-arc


The GitHub documentation for a deployment.yml for a GH runner does not specify an image, I'm not sure how an image definition will go for campers using an image they created from chapter 2.4
