### ISSUE TITLE
Swap Aritfactory out for a FOSS alternative

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#318]
Artifactory looks to no longer be free. It has a 14 day trial but that is no good since we ask apprentices to use this server multiple times in the bootcamp. 

Sonatype Nexus Repository -- Looks like a popular FOSS alternative

**Comment by amber-beasley-liatrio** [comment]
Following these directions from Frog I was able to install open source Artifactory via Docker

https://jfrog.com/help/r/jfrog-installation-setup-documentation/install-artifactory-single-node-with-docker

**Comment by jburns24** [comment]
hosting options are limited in the OSS version of Artifactory. Nexus OSS supports many repository types ootb in its OSS version

**Comment by jburns24** [comment]
Migrated from Artifactory to Nexus
