### ISSUE TITLE
Find or add dependency for Maven Integration exercise 5.3

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#325]
Throughout the bootcamp we use Spring Pet-Clinic as an example project. Specifically in the Maven sections 5.3 we use it to show a production like java deploy. Part of the learning is to manage dependent packages locally and depend on those. They recommend joda-time hibernate, and junit. Neither of those are dependencies of spring pet-clinic anymore. And the old liatrio fork does not compile ootb. 

- So we can try to maintain an old fork (not sure what work is going to go into this)
- we can find new dependencies in the pet-clinic project to build locally and depend on (I spent about an hour on this and didn't find one that was small and easy to depend on)
-  we can just arbitrarily add a dependency to the project (might be the easiest)

**Comment by amber-beasley-liatrio** [comment]
For the sake of knowing what we have previously tried to manage, the old Liatrio fork of the Spring Pet-Clinic seems to have an arbitrary dependency on joda-time 

Seeing that the old fork is unbuilding and we probably would see another Liatrio fork get too old to work. It might be best to utilize repos managed by others? 

... or use very simple Java projects (even homemade with actual dependencies on homemade java builds)

**Comment by jburns24** [comment]
@amber-beasley-liatrio I agree. Since starting here I have mostly heard grumbles regarding our maintained forks. And it is my understanding that we have invested engineering effort to 'make them work' in the past. I am all for pointing campers to community maintained example projects. 

Regarding this card we can close it. You addressed the specific concern with the changes you made to 5.3.2 (pointing to the official spring pet-clinic and arbitrarily asking campers to add joda-time).
