### ISSUE TITLE
Section 6.2.4 of Bootcamp

### ISSUE THREAD

**Issue by densellp** [liatrio/devops-bootcamp#350]
There is an issue in this section where the project dromedary currently does not function properly. When attempting to run npm install the following errors occur: 

![Image](https://github.com/liatrio/devops-bootcamp/assets/89417264/d495babf-efc1-45c3-a881-d45d22902954)

When attempting to use --force or --legacy-peer-deps errors continue to occur. 

If npm install does work using the previous 2 options running the program causes this error: 

![Image](https://github.com/liatrio/devops-bootcamp/assets/89417264/065a7912-fe86-4bc2-850f-04853e8be68f)

Another program may need to be used or this one needs to be fixed.

**Comment by jburns24** [comment]
@densellp Thank you for reporting this issue. Given the learning objective of this section this should be a pretty easy replacement. Unless this repo is critical for something else it does not seem worth it to update the repo

**Comment by densellp** [comment]
Section has been fixed, here is the PR for it: https://github.com/liatrio/devops-bootcamp/pull/383
