### ISSUE TITLE
Section 3.4 Exercise 1

### ISSUE THREAD

**Issue by mcbillings** [liatrio/devops-bootcamp#356]
Using Alpine as a base image appears to cause quite a bit of trouble when attempting to configure the self-hosted runner. This issue persists when having all of the dependencies outline by Microsoft installed. 

Errors: 

> 
> Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./bin/libcoreclr.so)
> Error relocating ./bin/libcoreclr.so: __isnan: symbol not found
> Error relocating ./bin/libcoreclr.so: __isnanf: symbol not found
> Libicu's dependencies is missing for Dotnet Core 6.0
> Execute sudo ./bin/installdependencies.sh to install any missing Dotnet Core 6.0 dependencies.
> /actions-runner/run-helper.sh: line 36: /actions-runner/bin/Runner.Listener: cannot execute: required file not found
> Exiting with unknown error code: 127
> Exiting runner...

**Comment by jburns24** [comment]
https://github.com/liatrio/devops-bootcamp/pull/599
