### ISSUE TITLE
Add New Section to Azure Chapter

### ISSUE THREAD

**Issue by densellp** [liatrio/devops-bootcamp#382]
There has been some discussion on adding a new section to the Azure Chapter of the DevOps Bootcamp. Some Ideas include the Azure App Service and Azure Functions, but there is no final decision yet.

**Comment by nsshaddox** [comment]
We can deploy a simple (serverless) application using App Service, use Azure Functions to handle some business logic, and use Logic Apps to automate tasks some tasks. 

Figuring out what application could handle this would be the first step.

**Comment by densellp** [comment]
@nsshaddox what part of the application would the azure function listen for?

**Comment by densellp** [comment]
Closing issue, at it has been resolved.
