### ISSUE TITLE
Add Code Review section to bootcamp

### ISSUE THREAD

**Issue by densellp** [liatrio/devops-bootcamp#388]
Add a section that talks about best practices and etiquette for code review. A section currently does not exist and developers need to rely on word of mouth or personal experience to understand the code review structure and how to do it properly.

**Comment by jburns24** [comment]
I think we could use some process and a section on best practices for everything that happens after you make a pull request. 
ie: how is the PR made visible (posted in slack? use the 'notify' tool in github?), what types of things should block a PR, how do we handle nit picks, what about style guidelines (only things that can be covered by linting or are there other conventions like no nested ternaries?)? should all comments be resolved before merging? Should all comments be responded to? Who merges the PR? 

Many of these things will be different from org to org but I think it would be cool if we came up with a PoV on how we want to handle Code Review. I feel like this ticket will be equal parts industry research and internal conversations
