### ISSUE TITLE
helm exercise 3 should be updated for newest versions of DKS

### ISSUE THREAD

**Issue by meher-liatrio** [liatrio/devops-bootcamp#509]
The latest version of the dis-ui could not be properly deployed to a cluster.
Either an old image should be used, or the dks-ui should be updated so that it can be deployed with helm.

**Comment by jburns24** [comment]
This should be resolved with https://github.com/liatrio/dks-ui/pull/291/files

**Comment by jburns24** [comment]
https://github.com/liatrio/devops-bootcamp/pull/586
